name       : perl-unicode-linebreak
version    : '2019.001'
release    : 12
source     :
    - https://cpan.metacpan.org/authors/id/N/NE/NEZUMI/Unicode-LineBreak-2019.001.tar.gz : 486762e4cacddcc77b13989f979a029f84630b8175e7fef17989e157d4b6318a
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Unicode Line Breaking Algorithm
description: |
    Unicode Line Breaking Algorithm
builddeps  :
    - perl-mime-charset
    - perl-test-pod
rundeps    :
    - perl-mime-charset
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
