name       : perl-unicode-linebreak
version    : 2016.003
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/N/NE/NEZUMI/Unicode-LineBreak-2016.003.tar.gz : e64e2d990a8cc90f8a387866509c35a93c50b812f5a2e60f3d9deb947a71dc24
license    : GPL-2.0
component  : programming.perl
summary    : Unicode Line Breaking Algorithm
description: |
    Unicode Line Breaking Algorithm
rundeps    :
    - perl-mime-charset
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
