name       : perl-unicode-linebreak
version    : '2018.003'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/N/NE/NEZUMI/Unicode-LineBreak-2018.003.tar.gz : 860c92ff3e710f0a1ca3e7067dba3734540dfb5cb932936536225f7ffca571b1
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Unicode Line Breaking Algorithm
description: |
    Unicode Line Breaking Algorithm
builddeps  :
    - perl-mime-charset
    - perl-test-pod
rundeps    :
    - perl-mime-charset
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
